services:
  fastify-app:
    build: ./fastify-docker
    ports:
      - "8000:3000"
    volumes:
      - ./fastify-docker:/app  # Mount local project folder into the container
      - /app/node_modules  # Prevent overwriting node_modules
    working_dir: /app
    command: npm run dev  # Run with hot reload
